### ISSUE TITLE
How does h compare to CDPATH?

### ISSUE THREAD

**Issue by pwaller** [zimbatm/h#1]
Hi!

If I am comfortable using `CDPATH=`, does `h` bring something to the table?

For example, I have mine set to this:

```
CDPATH=.:~/.local/src/github.com/pwaller:~/.local/src/github.com/scraperwiki:~/.local/src/github.com:~/.local/src
```

I guess one disadvantage is that it breaks tab completion when you're just trying to cd within `.`, but I've found this a small overhead.

**Comment by zimbatm** [comment]
Hey @pwaller !

I didn't know about CDPATH. Is it bash specific ? I should add a section about it in the doc.

The difference is that `h` also clones the appropriate repo. I spend quite a bit of time forking repos to fix bugs left and right so it's useful to me to just run `h direnv/direnv` for example and if it doesn't exist the project gets cloned. In both case my current directory is changed to `~/code/github.com/direnv/direnv` so I don't have to worry whenever the project has already been checked-out or not. It saves me a bit of cognitive effort.

Workflow is quite personal so I don't expect much people to adopt this tool :)

**Comment by pwaller** [comment]
Interesting :)

**Comment by pwaller** [comment]
Closing since this is old and is not actionable.
