### ISSUE TITLE
Case sensitivity is awkward

### ISSUE THREAD

**Issue by grahamc** [zimbatm/h#2]
```
[grahamc@Petunia:~/projects/github.com]$ ls -la
drwxr-xr-x  6 grahamc users  6 Mar  4 08:17 nixos
drwxr-xr-x  3 grahamc users  3 Mar 14 17:12 NixOS
```

Almost certainly done by a clone via `h nixos/foo` and then an `h git@github.com:NixOS/bar.git`.

Maybe we could check if the `owner` already exists as a lowercased option?

**Comment by zimbatm** [comment]
ok I misread the bug report

**Comment by zimbatm** [comment]
it's tricky. How about using only lower-cased folder in the filesystem? It wouldn't be backward-compatible but I think it's ok.

**Comment by zimbatm** [comment]
That wouldn't work if other tools are checking out folders like `go get`. I guess the `mkdir -p` really has to be made case-insensitive.

**Comment by grahamc** [comment]
Another option for this GitHub special casing is attempt an API call to determine the canonical capitalization?

**Comment by zimbatm** [comment]
good idea

**Comment by danbst** [comment]
well now `h nixos/nixpkgs` doesn't work when I have `~/code/github.com/nixos/nixpkgs`, it tries to clone `NixOS/nixpkgs`. To be clear, I've renamed `NixOS` to `nixos` manually, because I try to avoid mixed-case.

This is minor though.

**Comment by zimbatm** [comment]
don't rename NixOS to nixos! :D

but yeah, I don't know that all cases can be satisfied easily.
