### ISSUE TITLE
`up` and symlinks

### ISSUE THREAD

**Issue by danbst** [zimbatm/h#3]
I have:
```
[danbst@station:~/code/github.com/nixos]$ ls -l
total 0
lrwxrwxrwx 1 danbst users 24 січ 19 16:39 nixpkgs -> /home/danbst/dev/nixpkgs
```
I jump into `~/code/github.com/nixos/nixpkgs/pkgs/top-level` and try to jump `up`:
```
[danbst@station:~/code/github.com/nixos/nixpkgs/pkgs/top-level]$ up

[danbst@station:~/dev/nixpkgs]$ 
```
I'm following symlink, which is awkward. I expected to end up in `~/code/github.com/nixos/nixpkgs`.

(kinda related, but won't help here - for a long time fish had same problem with `cd`, https://github.com/fish-shell/fish-shell/issues/3350)

**Comment by zimbatm** [comment]
hmm yeah that's awkward. Not sure what the problem is...

**Comment by zimbatm** [comment]
it looks like `Pathname.pwd` and `Dir.pwd` resolve the symlinks

**Comment by zimbatm** [comment]
ruby calls `getcwd()` internally, which returns the resolved current directory. This is so weird, check this out:

setup:
```
cd /tmp
mkdir foo
ln -s foo bar
cd /tmp/bar
```
now:
```
$ pwd
/tmp/bar
$ strace pwd 2>/dev/null
/tmp/foo
```
